/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLugaresIndexRouteImport } from './routes/_authenticated/lugares/index'
import { Route as AuthenticatedLugaresNovoRouteImport } from './routes/_authenticated/lugares/novo'
import { Route as AuthenticatedLugaresIdRouteImport } from './routes/_authenticated/lugares/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLugaresIndexRoute =
  AuthenticatedLugaresIndexRouteImport.update({
    id: '/lugares/',
    path: '/lugares/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLugaresNovoRoute =
  AuthenticatedLugaresNovoRouteImport.update({
    id: '/lugares/novo',
    path: '/lugares/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLugaresIdRoute = AuthenticatedLugaresIdRouteImport.update({
  id: '/lugares/$id',
  path: '/lugares/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lugares/$id': typeof AuthenticatedLugaresIdRoute
  '/lugares/novo': typeof AuthenticatedLugaresNovoRoute
  '/lugares/': typeof AuthenticatedLugaresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/home': typeof AuthenticatedHomeRoute
  '/lugares/$id': typeof AuthenticatedLugaresIdRoute
  '/lugares/novo': typeof AuthenticatedLugaresNovoRoute
  '/lugares': typeof AuthenticatedLugaresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/lugares/$id': typeof AuthenticatedLugaresIdRoute
  '/_authenticated/lugares/novo': typeof AuthenticatedLugaresNovoRoute
  '/_authenticated/lugares/': typeof AuthenticatedLugaresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/home'
    | '/lugares/$id'
    | '/lugares/novo'
    | '/lugares/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/home'
    | '/lugares/$id'
    | '/lugares/novo'
    | '/lugares'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/home'
    | '/_authenticated/lugares/$id'
    | '/_authenticated/lugares/novo'
    | '/_authenticated/lugares/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lugares/': {
      id: '/_authenticated/lugares/'
      path: '/lugares'
      fullPath: '/lugares/'
      preLoaderRoute: typeof AuthenticatedLugaresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lugares/novo': {
      id: '/_authenticated/lugares/novo'
      path: '/lugares/novo'
      fullPath: '/lugares/novo'
      preLoaderRoute: typeof AuthenticatedLugaresNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lugares/$id': {
      id: '/_authenticated/lugares/$id'
      path: '/lugares/$id'
      fullPath: '/lugares/$id'
      preLoaderRoute: typeof AuthenticatedLugaresIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLugaresIdRoute: typeof AuthenticatedLugaresIdRoute
  AuthenticatedLugaresNovoRoute: typeof AuthenticatedLugaresNovoRoute
  AuthenticatedLugaresIndexRoute: typeof AuthenticatedLugaresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLugaresIdRoute: AuthenticatedLugaresIdRoute,
  AuthenticatedLugaresNovoRoute: AuthenticatedLugaresNovoRoute,
  AuthenticatedLugaresIndexRoute: AuthenticatedLugaresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
